name: Profile 3D Contributions

on:
  schedule:
    # Se ejecuta cada día a las 00:00 JST (15:00 UTC)
    - cron: "0 15 * * *"
  workflow_dispatch:  # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Genera los gráficos 3D
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # Commit y push automáticos
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "update 3d contributions" || echo "no changes"
          git push
